survey/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Default path is /survey/ which invokes index view without any params
    path('', views.index, name="index"),

    # API GET endpoint for returning popular survey among existing surveys.
    # This endpoint can also be used as a web hook in future. Currently it is used within the application.
    path('get_popular_survey/', views.get_popular_survey, name="get_popular_survey"),

    # API GET endpoint for returning survey objects along with corresponding questions and choices.
    # This endpoint can also be used as a web hook in future. Currently it is used within the application.
    path('get_all_surveys/', views.get_all_surveys, name="get_all_surveys"),

    # This is the view hook to submit survey form,
    # update entities based on the submitted form and redirect to success page
    path('submit_survey/', views.submit_survey, name="submit_survey"),

    # This is the generic route for rendering all partial views without params
    # All routes are intercepted by index view middleware and respective partial view will be rendered accordingly
    # Note: This is a work around as at this point I could not find a better solution
    # or documentation to create partial views
    path('<str:partial_view>/', views.index, name="index/partial_view"),

    # This is the generic route for rendering partial views with id parameter
    path('<str:partial_view>/<int:pk>', views.index, name="index/partial_view/id"),
]

surveymainapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('survey.urls'))
]

survey/models.py
from django.db import models
from django.utils import timezone
import datetime


class Survey(models.Model):
    """Class to encapsulate Survey entity
    Attributes:
        name: character field with max_length=200
        published_on: datetime field
    """

    name = models.CharField(max_length=200)
    published_on = models.DateTimeField("Published datetime")

    def __str__(self):
        return self.name    

class Question(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)
    created_on = models.DateTimeField('Creation Date Time')

    def __str__(self):
        return self.question_text

    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    created_on = models.DateTimeField('creation datetime')

    def __str__(self):
        return self.choice_text


class YesNoChoices(models.Model):
    YES = 'Yes'
    NO = 'No'
    NONE = 'None'

    CHOICES = [
        (YES, 'yes'),
        (NO, 'no'),
        (NONE, 'None'),
    ]

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    client_choices = models.CharField(max_length=4, choices=CHOICES, default=None)

    def __str__(self):
        return self.client_choices
    

survey/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse, JsonResponse
from django.template.loader_tags import register
from django.views.decorators.http import require_http_methods
from django.utils import timezone
from django.core import serializers
import operator


from .models import Survey, Question, Choice, YesNoChoices


all_partial_views = ['about', 'all_surveys', 'survey_details', 'submit_success']


@require_http_methods(["GET"])
def index(request, partial_view=None, pk=None):
    if partial_view is None:
        partial_view = 'about'
        return render(request, 'survey/index.html', {"partial_view": partial_view, "pk": pk})
    elif all_partial_views.count(partial_view) == 0:
        raise Http404('Partial View not found!')
    elif partial_view == "survey_details" and pk is None:
        raise Http404('Invalid Address! Page Not Found')
    else:
        return render(request, 'survey/index.html', {"partial_view": partial_view, "pk": pk})


@register.inclusion_tag('survey/surveys.html', takes_context=True)
def all_surveys(context):
    surveys = Survey.objects.all()
    return {'surveys': surveys}


@register.inclusion_tag('survey/about.html', takes_context=True)
def about(context):
    return {}


@register.inclusion_tag('survey/survey_details.html', takes_context=True)
def survey_details(context, survey_id):
    survey = Survey.objects.get(id=survey_id)
    return {'survey': survey}


@register.inclusion_tag('survey/submit_success.html', takes_context=True)
def submit_success(context):
    return {}


@require_http_methods(["POST"])
def submit_survey(request):
    form_data = request.POST.copy()
    # Example: {'csrfmiddlewaretoken': ['idT13LGpggg78Yr0rU3vSkT1PQxnM9hT7z97FvuZEBb
    # IU2acygAUr2W3FE9SCGbk'], '1': ['choice/3'], '2': ['choice/5']}
    form_items = list(form_data.items())
    print("form_items", form_items)
    form_items.pop(0)  # the first element is the csrf token. Therefore omit it.
    survey = None
    for item in form_items:
        # Here in 'choice/3', '3' is '<choice_id>'.
        choice_str, choice_id = item
        choice_id = int(choice_id.split('/')[1])
        choice = Choice.objects.get(id=choice_id)
        if survey is None:
            survey = choice.question.survey
        # choice.votes = choice.votes + 1
        choice.save()
    # if survey is not None:
    #     participant = Participant(survey=survey, participation_datetime=timezone.now())
    #     participant.save()
    return redirect('/submit_success/')


@require_http_methods(["GET"])
def get_popular_survey(request):
    popular_survey_id = None
    popular_survey = None
    surveys = Survey.objects.all()
    survey_participants_dict = {}
    for survey in surveys:
        num_participants = Participant.objects.filter(survey=survey).count()
        survey_participants_dict[survey.id] = num_participants
    if len(survey_participants_dict) > 0:
        popular_survey_id = max(survey_participants_dict.items(), key=operator.itemgetter(1))[0]
    if popular_survey_id is not None:
        popular_survey = serializers.serialize("json", surveys.filter(id=popular_survey_id))
    return JsonResponse(popular_survey, safe=False)


@require_http_methods(["GET"])
def get_all_surveys(request):
    surveys = Survey.objects.all()
    questions = Question.objects.all()
    choices = Choice.objects.all()
    yesnochoices = YesNoChoices.objects.all()

    return JsonResponse({"surveys": serializers.serialize("json", surveys),
                         "questions": serializers.serialize("json", questions),
                         "choices": serializers.serialize("json", choices),
                         "yesnochoices" : serializers.serialize("json", yesnochoices),
                         })

survey/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="rtl" lang="fa">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/survey-app.css' %}">
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <title>نظرسنجی</title>
</head>

{% load static %}
<body>

    {% block content %}
    {% endblock content %}

</body>
</html>

survey/templates/survey/about.html
{% extends 'base.html' %}


{% block content %}

<div class="card">
    {% load static %}
    <div class="card-body">
      <h5 class="card-title">درباره پرسشنامه</h5>
      <p class="card-text">آیا تابه حال شنیده‌اید که شخصی خود را به عنوان یک INTJ یا ESTP توصیف کرده باشد و شما معنی آن را ندانید؟ آنچه که این افراد می گویند، نوع شخصیت آن‌ها بر اساس شاخص تست مایرز-بریگز یا به اختصار، تست MBTI است.

        تست MBTI، یک پرسش‌نامه روان‌سنجی فردی است که برای شناسایی نوع شخصیت، نقاط قوت و اولویت‌های افراد طراحی شده است. این تست توسط ایزابل مایرز (Isabel Myers) و مادرش کاترین بریگز (Katherine Briggs) و بر اساس کارشان بر روی تئوری کارل یونگ (Carl Jung) درمورد انواع شخصیت تهیه شده است.
        
        امروزه، تست MBTI به‌عنوان یکی از از پرکاربردترین ابزارهای روان‌شناسی در دنیا شناخته می‌شود.
    </div>
  </div>

{% endblock content %}

survey/templates/survey/index.html
{% extends 'base.html' %}


{% block content %}
    <nav class="navbar navbar-expand-lg dark" style="background-color: #333;">
      <a class="navbar-brand survey-navbar-link" href="#">نظرسنجی</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if partial_view == "about" %}
                <li class="nav-item active">
                    <a class="nav-link survey-navbar-link" href="/about/">درباره <span class="sr-only">(current)</span></a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link survey-navbar-link" href="/about/">درباره</a>
                </li>
            {% endif %}
            {% if partial_view == "all_surveys" %}
                <li class="nav-item active">
                    <a class="nav-link survey-navbar-link" href="/all_surveys/">پرسشنامه <span class="sr-only">(current)</span></a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link survey-navbar-link" href="/all_surveys/">پرسشنامه</a>
                </li>
            {% endif %}
            <li class="nav-item">
                    <a class="nav-link survey-navbar-link" href="/admin/">صفحه ادمین</a>
            </li>

<!--          <li class="nav-item dropdown">-->
<!--            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--              Dropdown-->
<!--            </a>-->
<!--            <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--              <a class="dropdown-item" href="#">Action</a>-->
<!--              <a class="dropdown-item" href="#">Another action</a>-->
<!--              <div class="dropdown-divider"></div>-->
<!--              <a class="dropdown-item" href="#">Something else here</a>-->
<!--            </div>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link disabled" href="#">Disabled</a>-->
<!--          </li>-->
        </ul>
<!--        <form class="form-inline my-2 my-lg-0">-->
<!--          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--        </form>-->
      </div>
    </nav>
        {% if partial_view == 'about' %}
            {% about %}
        {% endif %}
        {% if partial_view == 'all_surveys' %}
            {% all_surveys %}
        {% endif %}
        {% if partial_view == 'survey_details' %}
            {% survey_details pk %}
        {% endif %}
        {% if partial_view == 'submit_success' %}
            {% submit_success %}
        {% endif %}

{% endblock content %}

survey/templates/survey/submit_success.html
{% extends 'base.html' %}


{% block content %}

<div class="card">
    <!-- {% load static %} -->
    <!-- <img class="card-img-top survey-about-img" src="{% static 'img/thank-you.jpg' %}" alt="Card image cap"> -->
    <div class="card-body">
      <p class="card-text">ممنون از مشارکت شما. تمام حقوق مادی و معنوی شما حفظ خواهد شد.</p>
      <a href="/all_surveys" class="btn btn-primary">یک تست دیگر بدهدید؟</a>
    </div>
  </div>

{% endblock content %}

survey/templates/survey/survey_details.html
{% extends 'base.html' %}


{% block content %}
<div class="card survey-form-card">
    <h5 class="card-header">{{survey.name}}</h5>
    <div class="card-body">
        <p class="card-text">از مشارکت شما ممنونیم</p>
        <form action="/submit_survey/" method="post">
        {% csrf_token %}
        {% for question in survey.question_set.all %}
            <fieldset class="form-group">
              <div class="row">
                <legend class="col-form-label col-md-6 pt-0">{{question.question_text}}</legend>
                <div class="col-md-6">
                  {% for choice in question.choice_set.all %}
                      <div class="form-check">
                        <input class="form-check-input" type="radio" name="{{question.id}}"
                               id="{{question.id}}{{choice.id}}" value="choice/{{choice.id}}" aria-describedby="radioHelp">
                        <label class="form-check-label" for="{{question.id}}{{choice.id}}">
                          {{choice.choice_text}}
                        </label>
                      </div>
                  {% endfor %}
                  <small id="radioHelp" class="form-text text-muted">لطفا یکی از گزینه ها را انتخاب کنید.</small>
                </div>
              </div>
            </fieldset>
            <hr/>
        {% endfor %}
        <div class="form-group row">
          <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">ثبت</button>
          </div>
        </div>
      </form>
    </div>
  </div>

{% endblock content %}

survey/templates/survey/surveys.html
{% extends 'base.html' %}


{% block content %}

<div class="card" dir="rtl">
    <h5 class="card-header">پرسشنامه های در دسترس</h5>
    <div class="card-body">
        <p class="card-text">لطفا به پرسشنامه های زیر پاسخ دهید</p>
        <ul>
          {% for survey in surveys %}
              <li>
                  <div class="card">
                    <div class="card-body">
                      <h5 class="card-title"><a href="/survey_details/{{survey.pk}}">{{survey.name}}</a></h5>
                    </div>
                  </div>
              </li>
          {% endfor %}
        </ul>
    </div>
  </div>

{% endblock content %}